#pragma config(Sensor, dgtl1,  solenoid1,      sensorDigitalOut)
#pragma config(Sensor, dgtl2,  solenoid2,      sensorDigitalOut)
#pragma config(Motor,  port2,           drvLeft,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           releaseMotor,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           drvRight,      tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "constants.c"
#include "behaviors.c"
#include "joystick.c"

task main()
{

	while (true) {                        //Always active checking below functions.
		if (!killSwitchControl()) {       //Checks to see if kill switch is activated or not, if not it continues.
			driveControl();               //Controls the movement of the bot - see file "joystick.c"
			cannonControl();			  //When button on joystick is pressed, retract or extend the cylinder
			releaseControl();             //Used to release the cannon by turning the motor on cannon head
		} else {
			halt();						  //When the kill switch on the joystick is activated, it puts the program in a stopped state until deactivated.
		}
	}

}
