#pragma config(Sensor, dgtl1,  solenoid1,      sensorDigitalOut)
#pragma config(Sensor, dgtl2,  solenoid2,      sensorDigitalOut)
#pragma config(Motor,  port1,           drvLeft,        tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           drvRight,        tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "constants.c";
#include "behaviors.c";
#include "joystick.c"

task main()
{

	while (true) {
		driveControl();
		cannonControl();
	}

}
